name: property_manager_app
description: "Property Manager App is a Flutter application designed to help users manage their properties efficiently. It provides features for tracking property details, expenses, and maintenance schedules."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.4
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  logger: ^2.6.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  redacted: ^1.0.13
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Testing
  mocktail: ^1.0.4
  build_runner: ^2.5.4



flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


# Splash Screen Configuration    
flutter_native_splash:
  color: "#F2F5F7"
  image: assets/images/splash.png
  android_12:
    color: "#F2F5F7"
    image: assets/images/android_12_splash.png

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptative_icon_foreground: "assets/images/logo_foreground.png"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
