// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaz4dT2orDn1qsz5Em9y1UgEYKP7KVETY',
    appId: '1:166209070190:web:e0b01a988e6fd663e9f27f',
    messagingSenderId: '166209070190',
    projectId: 'propertymanager-5c653',
    authDomain: 'propertymanager-5c653.firebaseapp.com',
    storageBucket: 'propertymanager-5c653.firebasestorage.app',
    measurementId: 'G-TS9Y077JZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4auLXct6xKgEaDUQUp_BMbfwA6RwGTcU',
    appId: '1:166209070190:android:efc6ed1a6f291130e9f27f',
    messagingSenderId: '166209070190',
    projectId: 'propertymanager-5c653',
    storageBucket: 'propertymanager-5c653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvrIUSjW0FI0q0fn845Cs-E3GkYOzIz0',
    appId: '1:166209070190:ios:3597c2b9e70c38b3e9f27f',
    messagingSenderId: '166209070190',
    projectId: 'propertymanager-5c653',
    storageBucket: 'propertymanager-5c653.firebasestorage.app',
    iosBundleId: 'com.example.propertyManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvrIUSjW0FI0q0fn845Cs-E3GkYOzIz0',
    appId: '1:166209070190:ios:3597c2b9e70c38b3e9f27f',
    messagingSenderId: '166209070190',
    projectId: 'propertymanager-5c653',
    storageBucket: 'propertymanager-5c653.firebasestorage.app',
    iosBundleId: 'com.example.propertyManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaz4dT2orDn1qsz5Em9y1UgEYKP7KVETY',
    appId: '1:166209070190:web:f6333a4f8e349e89e9f27f',
    messagingSenderId: '166209070190',
    projectId: 'propertymanager-5c653',
    authDomain: 'propertymanager-5c653.firebaseapp.com',
    storageBucket: 'propertymanager-5c653.firebasestorage.app',
    measurementId: 'G-6HZM963FPP',
  );
}
